# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tak < Formula
  desc "Git worktree manager with pinning, tmux integration, and lifecycle tools"
  homepage "https://github.com/mzner/tak"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mzner/tak/releases/download/v1.0.0/tak_1.0.0_darwin_amd64.tar.gz"
      sha256 "3315d7c4d2e72c4d72ad6a09707f83886f19ad8536cf01291b87b381a47bc6b2"

      define_method(:install) do
        bin.install "tak"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mzner/tak/releases/download/v1.0.0/tak_1.0.0_darwin_arm64.tar.gz"
      sha256 "7197db67bcb7652a7b2c0122372c1bdedfe64eac43ea516d173a14750a7b8a04"

      define_method(:install) do
        bin.install "tak"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mzner/tak/releases/download/v1.0.0/tak_1.0.0_linux_amd64.tar.gz"
      sha256 "8914fcd5effc4dd900f235cdd903d81b0aaa33b832b37705e4eadf5cf3add2ef"
      define_method(:install) do
        bin.install "tak"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mzner/tak/releases/download/v1.0.0/tak_1.0.0_linux_arm64.tar.gz"
      sha256 "8fe73d6298966a6b1c76c35fa9f5625f46a13eda5156b0aad9a050816c6c4d06"
      define_method(:install) do
        bin.install "tak"
      end
    end
  end
end
