# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocis-cli" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "aa2c8300ebbdec3b999c543f953ddcfe461bb31ffcb4f59475eecbb17c280610"
      url "https://github.com/mzner/ocis-cli/releases/download/v#{version}/ocis-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "664093cb614b15cda0c5504ce96db8d756d9f2bbe428434e5701704c1f35fdc3"
      url "https://github.com/mzner/ocis-cli/releases/download/v#{version}/ocis-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c933b9823e0ebc8665d83a49875b13e3f0abd547d7957ec9efe866127f648331"
      url "https://github.com/mzner/ocis-cli/releases/download/v#{version}/ocis-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "68042faaa6adbef4b690bf98a6f59fa7b0162ea90fef7ab751f7632761086e42"
      url "https://github.com/mzner/ocis-cli/releases/download/v#{version}/ocis-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ocis-cli"
  desc "Script-friendly CLI for oCIS-compatible servers"
  homepage "https://github.com/mzner/ocis-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocis"

  generate_completions_from_executable "ocis", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
